/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import entities.Worker;
import entities.Client;
import implement.ImplPerson;
import implement.ImplClient;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LAB REDES
 */
public class ClientGUI extends javax.swing.JPanel {

DefaultTableModel modelo;

//ImplPerson ip = new ImplPerson();    
ImplClient ic = new ImplClient();

    /**
     * Creates new form Client
     */
    public ClientGUI() {
        initComponents(); // agrega componentes al lienzo
         ReporteDataDB();  // consulta a db


        jButtonActualizar.setVisible(false);
        jButtonDelete.setVisible(false);
        jTextField_id.setVisible(false);
        jPanelFormulario.setVisible(true);
    }

    public void ReporteDataDB(){
            modelo = new DefaultTableModel();
            modelo.addColumn("Codigo cliente");
            modelo.addColumn("Tipo cliente");
            modelo.addColumn("perdona id");
            modelo.addColumn("id");
            modelo.addColumn("client");


                for (Client client : ic.reporteClients()) {
                    Object[] fila = new Object[7];
                    fila[0] = client.getClient_codigocliente();
                    fila[1] = client.getClient_tipo();
                    fila[2] = client.getClient_person_id();
                    fila[3] = "******";
                    fila[4] = client.getClient_id();

                    System.out.println("RECUPEANDOO _>>>>");

                    modelo.addRow(fila);
                }
            jTableWorkers.setModel(modelo); 
        
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFormulario = new javax.swing.JPanel();

        jLabel_titulo = new javax.swing.JLabel();
        JL_codigo_cliente = new javax.swing.JLabel();
        jLabel_nro = new javax.swing.JLabel();
        jLabel_nro1 = new javax.swing.JLabel();
        jLabel_nro2 = new javax.swing.JLabel();



        JTF_codigo_client = new javax.swing.JTextField();
        JTF_tipo_cliente = new javax.swing.JTextField();
        //jTextField_materno = new javax.swing.JTextField();
        //jTextField_paterno = new javax.swing.JTextField();
        //jTextField_usuario = new javax.swing.JTextField();
        //jPasswordField_paswd = new javax.swing.JPasswordField();
        jButton_grabar = new javax.swing.JButton();
        

        jTableWorkers = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        
        jTextField_id = new javax.swing.JTextField();
        jButtonActualizar = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();

        jLabel_titulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_titulo.setForeground(new java.awt.Color(204, 102, 0));
        jLabel_titulo.setText("Formulario Cliente");
        jLabel_titulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        JL_codigo_cliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JL_codigo_cliente.setForeground(new java.awt.Color(204, 102, 0));
        
        JL_codigo_cliente.setText("Codigo Cliente:");

   //     jLabel_paterno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
     //   jLabel_paterno.setForeground(new java.awt.Color(204, 102, 0));
       // jLabel_paterno.setText("Ap. Paterno:");

        //jLabel_materno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        //jLabel_materno.setForeground(new java.awt.Color(204, 102, 0));
        //jLabel_materno.setText("Ap. Materno:");

        jLabel_nro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_nro.setForeground(new java.awt.Color(204, 102, 0));
        jLabel_nro.setText("Tipo cliente:");

        jLabel_nro1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_nro1.setForeground(new java.awt.Color(204, 102, 0));
        jLabel_nro1.setText("Persona :");

        /*jLabel_nro2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_nro2.setForeground(new java.awt.Color(204, 102, 0));
        jLabel_nro2.setText("Contraseña:");
        */

        jButton_grabar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_grabar.setForeground(new java.awt.Color(204, 102, 0));
        jButton_grabar.setText("Grabar");

        jButton_grabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_grabarActionPerformed(evt);
            }
        });



        jButtonActualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonActualizar.setForeground(new java.awt.Color(204, 102, 0));
        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });


        jButtonDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDelete.setForeground(new java.awt.Color(204, 102, 0));
        jButtonDelete.setText("Eliminar");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });




        javax.swing.GroupLayout jPanelFormularioLayout = new javax.swing.GroupLayout(jPanelFormulario);

        jPanelFormulario.setLayout(jPanelFormularioLayout);
        
        jPanelFormularioLayout.setHorizontalGroup(
            jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFormularioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(jPanelFormularioLayout.createSequentialGroup()
                .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelFormularioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_grabar, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelFormularioLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          //                  .addComponent(jLabel_paterno)
                            .addComponent(JL_codigo_cliente)
            //                .addComponent(jLabel_materno)
                            .addComponent(jLabel_nro)
                            .addComponent(jLabel_nro1)
                            .addComponent(jLabel_nro2))
                        .addGap(31, 31, 31)
                        .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTF_codigo_client)
                            //.addComponent(jTextField_materno, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            //.addComponent(jTextField_paterno, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            //.addComponent(jTextField_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(JTF_tipo_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            //.addComponent(jPasswordField_paswd)
                            
                            .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButtonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton_grabar, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                )

                            )))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanelFormularioLayout.setVerticalGroup(
            jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_codigo_cliente)
                    .addComponent(JTF_codigo_client, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    //.addComponent(jTextField_paterno, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    //.addComponent(jLabel_paterno)
                    )
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    //.addComponent(jTextField_materno, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    //.addComponent(jLabel_materno)
                    )
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF_tipo_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_nro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    //.addComponent(jTextField_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_nro1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    //.addComponent(jPasswordField_paswd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_nro2))
                .addGap(45, 45, 45)
                .addComponent(jButtonDelete)
                .addComponent(jButton_grabar)

                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonActualizar)
                .addGap(11, 11, 11)


                .addContainerGap())
        );


        jTableWorkers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo cliente", "Tipo cliente", "PersonaID", "Ruc / Dni", "Usuario", "Contraseña", "Id"
            }
        ));
        jTableWorkers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableWorkersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableWorkers); // agregando tabla al panel


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);

        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
//
                .addContainerGap(62, Short.MAX_VALUE))
        );


        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
//


                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                )
        );

        
        
    }// </editor-fold>//GEN-END:initComponents

    private void jTableWorkersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableWorkersMouseClicked
        

        int row=jTableWorkers.getSelectedRow();
        
        System.out.print("hellowwwww"+row);
        String codigo  = jTableWorkers.getValueAt(row, 0).toString();
        System.out.print("COd"+codigo);
        String tipo  = jTableWorkers.getValueAt(row, 1).toString();
        System.out.print("tipo"+tipo);
        String idPerson  = jTableWorkers.getValueAt(row, 2).toString();
        System.out.print("idPers"+idPerson);
        //String idClient  = jTableWorkers.getValueAt(row, 3).toString();
        //System.out.print("iclient"+idClient);
        
        
        String idClient  = jTableWorkers.getValueAt(row, 4).toString();
        System.out.print("iddd"+idClient);
        JTF_codigo_client.setText(codigo);
        JTF_tipo_cliente.setText(tipo);
        jTextField_id.setText(idClient);
        
    

        jButton_grabar.setVisible(false);        
        jButtonActualizar.setVisible(true);
        jButtonDelete.setVisible(true);
                
    }

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed

            
            System.out.print(jTextField_id.getText()+"sfdsfsdfsdf");
            ic.eliminarCliente(jTextField_id.getText());
            int row=jTableWorkers.getSelectedRow();
            jTableWorkers.removeAll();
    }//GEN-LAST:event_jButtonDeleteActionPerformed


    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        System.out.print("holassss"+jTextField_id.getText());
             
         if(JTF_codigo_client.getText().equals("")||
           JTF_tipo_cliente.getText().equals("")
           ){
            JOptionPane.showMessageDialog(null, "Ingrese los datos completos");
        
        }else{
        
            Client cli = new Client();
            cli.setClient_id(jTextField_id.getText());
            cli.setClient_codigocliente(JTF_codigo_client.getText());;
            cli.setClient_tipo(JTF_tipo_cliente.getText());
            cli.setPerson_id("jajajaja");
            
            
            ic.ActualizarCliente(cli);
            int row=jTableWorkers.getSelectedRow();
            updateOneReporteData(row);
            JOptionPane.showMessageDialog(null, "Se actualizo de manera satisfactoria");            
            limpiarJTextField();            
           // ReporteDataDB();
            
            
        }  
                
    }

    private void jButton_grabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_grabarActionPerformed
        // TODO add your handling code here:
        System.out.println("GUADRA");

        if(JTF_codigo_client.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Verifique los campos");

        }else{
        
            Client cli = new Client();

            cli.setClient_codigocliente(JTF_codigo_client.getText());
            cli.setClient_tipo(JTF_tipo_cliente.getText());
            cli.setPerson_id("nolotengo");      
            
            
            ic.guardarClient(cli);
            
            JOptionPane.showMessageDialog(null, "Se registro de manera satisfactoria");            
            AddOneReporteData();
            limpiarJTextField();            
            
        }   
    }//GEN-LAST:event_jButton_grabarActionPerformed

    public void AddOneReporteData(){
        Object[] fila = new Object[7];
                    fila[0] = JTF_codigo_client.getText();
                    fila[1] = JTF_tipo_cliente.getText();
                    fila[2] = "*******";
                    fila[3] = "*******";
                    fila[4] = "*******";
                    fila[5] = "*******";
                    fila[6] = "*******";

                    modelo.addRow(fila);
                
            jTableWorkers.setModel(modelo); 
    }

    public void limpiarJTextField(){
            JTF_codigo_client.setText("");
            JTF_tipo_cliente.setText("");
            
    }

    public void updateOneReporteData(int rowSelected){
        Object[] fila = new Object[7];
                    jTableWorkers.setValueAt(JTF_codigo_client.getText(), rowSelected, 0);
                    jTableWorkers.setValueAt(JTF_tipo_cliente.getText(), rowSelected, 1);
                    jTableWorkers.setValueAt("jaajaj", rowSelected, 2);
                    jTableWorkers.setValueAt("********", rowSelected, 3);
                    jTableWorkers.setValueAt(jTextField_id.getText(), rowSelected, 4);
                    
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_grabar;
  //  private javax.swing.JLabel jLabel_materno;
    private javax.swing.JLabel JL_codigo_cliente;
    private javax.swing.JLabel jLabel_nro;
    private javax.swing.JLabel jLabel_nro1;
    private javax.swing.JLabel jLabel_nro2;
//    private javax.swing.JLabel jLabel_paterno;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JPanel jPanelFormulario;
    // private javax.swing.JPasswordField jPasswordField_paswd;
    //private javax.swing.JTextField jTextField_materno;
    private javax.swing.JTextField JTF_codigo_client;
    private javax.swing.JTextField JTF_tipo_cliente;
    //private javax.swing.JTextField jTextField_paterno;
    //private javax.swing.JTextField jTextField_usuario;


    private javax.swing.JTextField jTextField_id;
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JTable jTableWorkers;

    private javax.swing.JScrollPane jScrollPane1;

    // End of variables declaration//GEN-END:variables
}
